const AllCourse = [
  {
    id: 1,
    CoureName: "Engineering Mathematics",
    InstructorName: "Mr. Franklin",
    price: "$50",
    rating: 4,
    numberOfStudents: "11,200",
    img: "/images/img-1.jpg",
    Instructor: "/images/avatar2.jpg",
  },
  {
    id: 2,
    CoureName: "Business Management",
    InstructorName: "Mr. Franklin",
    price: "$40",
    rating: 3,
    numberOfStudents: "20,000",
    img: "/images/img-2.jpg",
    Instructor: "/images/avatar2.jpg",
  },
  {
    id: 3,
    CoureName: "Marketing Strategy",
    InstructorName: "Mrs. Jane",
    price: "$35",
    rating: 2,
    numberOfStudents: "8,000",
    img: "/images/img-3.jpg",
    Instructor: "/images/avatar1.jpg",
  },
  {
    id: 4,
    CoureName: "Software Engineering",
    InstructorName: "Mrs. Gloria",
    price: "$40",
    rating: 5,
    numberOfStudents: "20,000",
    img: "/images/bg-img-1.jpg",
    Instructor: "/images/avatar3.jpg",
  },
  {
    id: 5,
    CoureName: "Graphics Design",
    InstructorName: "Mrs. Jane",
    price: "$15",
    rating: 3,
    numberOfStudents: "19,320",
    img: "/images/header.jpg",
    Instructor: "/images/avatar1.jpg",
  },
  {
    id: 6,
    CoureName: "Technical Drawing",
    InstructorName: "Mrs. Gloria",
    price: "$75",
    rating: 4,
    numberOfStudents: "19,320",
    img: "/images/blog-1.jpg",
    Instructor: "/images/avatar3.jpg",
  },
  {
    id: 7,
    CoureName: "Engineering Mathematics",
    InstructorName: "Mr. Franklin",
    price: "$50",
    rating: 4,
    numberOfStudents: "11,200",
    img: "/images/img-1.jpg",
    Instructor: "/images/avatar2.jpg",
  },
  {
    id: 8,
    CoureName: "Business Management",
    InstructorName: "Mr. Franklin",
    price: "$40",
    rating: 3,
    numberOfStudents: "20,000",
    img: "/images/img-2.jpg",
    Instructor: "/images/avatar2.jpg",
  },
  {
    id: 9,
    CoureName: "Marketing Strategy",
    InstructorName: "Mrs. Jane",
    price: "$35",
    rating: 2,
    numberOfStudents: "8,000",
    img: "/images/img-3.jpg",
    Instructor: "/images/avatar1.jpg",
  },
  {
    id: 10,
    CoureName: "Software Engineering",
    InstructorName: "Mrs. Gloria",
    price: "$40",
    rating: 5,
    numberOfStudents: "20,000",
    img: "/images/bg-img-1.jpg",
    Instructor: "/images/avatar3.jpg",
  },
  {
    id: 11,
    CoureName: "Graphics Design",
    InstructorName: "Mrs. Jane",
    price: "$15",
    rating: 3,
    numberOfStudents: "19,320",
    img: "/images/header.jpg",
    Instructor: "/images/avatar1.jpg",
  },
  {
    id: 12,
    CoureName: "Technical Drawing",
    InstructorName: "Mrs. Gloria",
    price: "$75",
    rating: 4,
    numberOfStudents: "19,320",
    img: "/images/blog-1.jpg",
    Instructor: "/images/avatar3.jpg",
  },
];

const recommendedCourses = [
  {
    id: 1,
    src: "/images/img-1.jpg",
    CoureName: "Technical Drawing",
    InstructorName: "Mrs. Gloria",
    price: "$75",
    rating: 4,
    numberOfStudents: "19,320",
    Instructor: "/images/avatar3.jpg",
  },
  {
    id: 2,
    src: "/images/img-2.jpg",
    CoureName: "Business Management",
    InstructorName: "Mr. Franklin",
    price: "$40",
    rating: 2,
    numberOfStudents: "20,000",
    Instructor: "/images/avatar2.jpg",
  },
  {
    id: 3,
    src: "/images/img-3.jpg",
    CoureName: "Marketing Strategy",
    InstructorName: "Mrs. Jane",
    price: "$35",
    rating: 2,
    numberOfStudents: "8,000",
    Instructor: "/images/avatar1.jpg",
  },
  {
    id: 4,
    src: "/images/bg-img-1.jpg",
    CoureName: "Software Engineering",
    InstructorName: "Mrs. Gloria",
    price: "$40",
    rating: 5,
    numberOfStudents: "20,000",
    Instructor: "/images/avatar3.jpg",
  },
  {
    id: 5,
    src: "/images/blog-1.jpg",
    CoureName: "Graphics Design",
    InstructorName: "Mrs. Jane",
    price: "$15",
    rating: 3,
    numberOfStudents: "19,320",
    Instructor: "/images/avatar1.jpg",
  },
  {
    id: 6,
    src: "/images/header.jpg",
    CoureName: " PhotoGraphy",
    InstructorName: "Mrs. Gloria",
    price: "$15",
    rating: 3,
    numberOfStudents: "19,600",
    Instructor: "/images/avatar3.jpg",
  },
  {
    id: 7,
    src: "/images/img-1.jpg",
    CoureName: "Technical Drawing",
    InstructorName: "Mrs. Jane",
    price: "$75",
    rating: 4,
    numberOfStudents: "19,320",
    Instructor: "/images/avatar1.jpg",
  },
  {
    id: 8,
    src: "/images/img-2.jpg",
    CoureName: "Business Management",
    InstructorName: "Mr. Franklin",
    price: "$40",
    rating: 3,
    numberOfStudents: "20,000",
    Instructor: "/images/avatar2.jpg",
  },
  {
    id: 9,
    src: "/images/img-3.jpg",
    CoureName: "Marketing Strategy",
    InstructorName: "Mrs. Jane",
    price: "$35",
    rating: 2,
    numberOfStudents: "8,000",
    Instructor: "/images/avatar3.jpg",
  },
  {
    id: 10,
    src: "/images/bg-img-1.jpg",
    CoureName: "Software Engineering",
    InstructorName: "Mrs. Gloria",
    price: "$40",
    rating: 5,
    numberOfStudents: "20,000",
    Instructor: "/images/avatar3.jpg",
  },
  {
    id: 11,
    src: "/images/blog-1.jpg",
    CoureName: "Graphics Design",
    InstructorName: "Mrs. Gloria",
    price: "$15",
    rating: 3,
    numberOfStudents: "19,320",
    img: "/images/header.jpg",
    Instructor: "/images/avatar3.jpg",
  },
  {
    id: 12,
    src: "/images/header.jpg",
    CoureName: " PhotoGraphy",
    InstructorName: "Mrs. Jane",
    price: "$15",
    rating: 3,
    numberOfStudents: "19,600",
    Instructor: "/images/avatar1.jpg",
  },
];

const instructors = [
  {
    id: 1,
    name: "Mr. Franklin",
    email: "franklyn@gmail.com",
    about:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit at nulla tenetur excepturi eveniet nam voluptatibus laudantium quas similique, natus deserunt, voluptatem quisquam quo possimus ipsa consectetur quos hic? Iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum exercitationem quae fugiat, aspernatur perspiciatis sequi nulla sint delectus velit molestiae qui repudiandae voluptatibus laborum corrupti quia sed nihil ducimus ut voluptas at non? Iusto, temporibus nostrum voluptatem nihil provident fugiat perspiciatis dolorem deserunt, corporis delectus repudiandae, fuga sint quaerat cupiditate?",
    Qualification: {
      university: "Havard",
      has: "PhD in Mathematics and Business Management",
    },
    Age: 27,
    from: "Florida",
  },
  {
    id: 2,
    name: "Mrs. Jane",
    email: "Jane@gmail.com",
    about:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit at nulla tenetur excepturi eveniet nam voluptatibus laudantium quas similique, natus deserunt, voluptatem quisquam quo possimus ipsa consectetur quos hic? Iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum exercitationem quae fugiat, aspernatur perspiciatis sequi nulla sint delectus velit molestiae qui repudiandae voluptatibus laborum corrupti quia sed nihil ducimus ut voluptas at non? Iusto, temporibus nostrum voluptatem nihil provident fugiat perspiciatis dolorem deserunt, corporis delectus repudiandae, fuga sint quaerat cupiditate?",
    Qualification: {
      university: "MIT",
      has: "PhD in Marketing and Graphic design",
    },
    Age: 23,
    from: "Las Vagas",
  },
  {
    id: 3,
    name: "Mrs. Gloria",
    email: "Gloria@gmail.com",
    about:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugit at nulla tenetur excepturi eveniet nam voluptatibus laudantium quas similique, natus deserunt, voluptatem quisquam quo possimus ipsa consectetur quos hic? Iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum exercitationem quae fugiat, aspernatur perspiciatis sequi nulla sint delectus velit molestiae qui repudiandae voluptatibus laborum corrupti quia sed nihil ducimus ut voluptas at non? Iusto, temporibus nostrum voluptatem nihil provident fugiat perspiciatis dolorem deserunt, corporis delectus repudiandae, fuga sint quaerat cupiditate?",
    Qualification: {
      university: "Stanford",
      has: "PhD in Software Engineering and Technical writing",
    },
    Age: 25,
    from: "London",
  },
];
export { AllCourse, recommendedCourses, instructors };
